FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD GitUnderstanding.jar /opt/GitUnderstanding/
EXPOSE 8080
WORKDIR /opt/GitUnderstanding/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "GitUnderstanding.jar"]
